![baby_names](baby_names.jpg)

How have American baby name tastes changed since 1920? Which names have remained popular for over 100 years, and how do those names compare to more recent top baby names? These are considerations for many new parents, but the skills you'll practice while answering these queries are broadly applicable. After all, understanding trends and popularity is important for many businesses, too!

You'll be working with data provided by the United States Social Security Administration, which lists first names along with the number and sex of babies they were given to in each year. For processing speed purposes, the dataset is limited to first names which were given to over 5,000 American babies in a given year. The data spans 101 years, from 1920 through 2020.

## The Data

### `baby_names`

| column         | type    | description                                                                  |
| -------------- | ------- | ------------------------------------------------------------------------ |
| `year`         | int     | year                                                                     |
| `first_name`   | varchar | first name                                                               |
| `sex`          | varchar | `sex` of babies given `first_name`                                       |
| `num`          | int     | number of babies of `sex` given `first_name` in that `year`              |

In [9]:
-- Run this code to view the data in baby_names
SELECT *
FROM baby_names
LIMIT 20;

    year first_name sex    num
0   1920       Mary   F  70982
1   1920    Dorothy   F  36643
2   1920      Helen   F  35097
3   1920   Margaret   F  27994
4   1920       Ruth   F  26101
5   1920    Mildred   F  18059
6   1920   Virginia   F  17314
7   1920  Elizabeth   F  15909
8   1920    Frances   F  15883
9   1920       Anna   F  14581
10  1920      Betty   F  14016
11  1920     Evelyn   F  13838
12  1920      Marie   F  12743
13  1920      Doris   F  11892
14  1920      Alice   F  11596
15  1920   Florence   F  10732
16  1920      Irene   F  10072
17  1920    Lillian   F  10049
18  1920     Louise   F   9179
19  1920       Rose   F   9011

In [10]:
-- Use this table for the answer to question 1:
-- List the overall top five names in alphabetical order and find out if each name is "Classic" or "Trendy."
SELECT first_name,
	SUM(num),
	CASE WHEN COUNT(year) > 50 THEN 'Trendy'
		ELSE 'Classic' END AS popularity_type
FROM baby_names
GROUP BY first_name
ORDER BY first_name ASC
LIMIT 5;

  first_name     sum popularity_type
0    Aaliyah   15870         Classic
1      Aaron  530592          Trendy
2    Abigail  338485         Classic
3       Adam  497293         Classic
4    Addison  107433         Classic

In [11]:
-- Use this table for the answer to question 2:
-- What were the top 20 male names overall, and how did the name Paul rank?
SELECT RANK() OVER(ORDER BY SUM(num) DESC) AS name_rank,
		first_name,
		SUM(num)
FROM baby_names
WHERE sex = 'M'
GROUP BY first_name
LIMIT 20;

    name_rank   first_name      sum
0           1        James  4748138
1           2         John  4510721
2           3       Robert  4495199
3           4      Michael  4278824
4           5      William  3614424
5           6        David  3571498
6           7      Richard  2414838
7           8       Joseph  2361382
8           9       Thomas  2166802
9          10      Charles  2112352
10         11  Christopher  2012792
11         12       Daniel  1824274
12         13      Matthew  1567204
13         14      Anthony  1344352
14         15       Donald  1280236
15         16         Mark  1265910
16         17         Paul  1218996
17         18       Steven  1216819
18         19       Joshua  1204236
19         20       Andrew  1157548

In [12]:
-- Use this table for the answer to question 3:
-- Which female names appeared in both 1920 and 2020?
SELECT first_name,
	COUNT(year) AS total_occurrences
FROM baby_names
WHERE year BETWEEN '1920' AND '2020' AND sex = 'F'
GROUP BY first_name;

    first_name  total_occurrences
0       Sophia                 22
1        Cindy                 15
2          Amy                 35
3      Carolyn                 37
4    Geraldine                 10
..         ...                ...
305    Frances                 35
306     Violet                  2
307  Josephine                 10
308     Angela                 37
309      Amber                 26

[310 rows x 2 columns]